package com.example.eventreader.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

@Entity
@Table(name = "products")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Getter
    private Long id;  // This is the PK auto generated by the DB
    @Getter
    @Setter
    private String type;
    @Getter
    @Setter
    private double price;
    @Getter
    @Setter
    private LocalDate startDate;
    @Getter
    @Setter
    private LocalDate endDate;

    @ManyToOne
    @JoinColumn(name="event_id")
    @JsonBackReference
    private Event event;  // This is the FK referencing the Event table
}
